### ISSUE TITLE
Implement the 'cp-tools genhtml' command

### ISSUE THREAD

**Issue by edsomjr** [edsomjr/competitive-problems-tools#13]
### Description:
Currently, cp-tools has the commands `genpdf` and `gentex`, where the files are compiled for PDF and LaTEX respectively.

It is desirable that the `genhtml` command compiles the files into HTML files, so that the problem can be viewed in a browser

This CLI command should work in the same way as `genpdf` and` gentex` commands.

The parameters for this command are:
- `-h / --help` to print to the terminal the parameters supported by the command
- `-b / --label` to define the problem labels. If omitted, the default label is `A`
- `-l / --list` to list all document classes (templates) available for use
- `-c / --class` to define the class (template) of the document that will be used in the compilation. If omitted, the default template will be `plain`
- `-g / --lang` to define the language of the document. If omitted, the default language will be `pt_BR`
- `-o / --output` to define the name of the output file that will be generated. If omitted, the output file will be `problem.html`
- `-t / --tutorial` to generate the problem solution file (in html, of course)
- `--no_autor` to omit the problem author in the output file
- `--no_contest` to omit the problem contest in the output file

### Acceptance criteria:

- [ ] It must document the implemented parameters
- [ ] The files must be standalone

### Tasks:

- [ ]  Implement a LaTeX to HTML converter or use a external command to make this conversion
- [ ]  Use MathJax to display mathematical formulas in HTML

**Comment by durvalcarvalho** [comment]
## Implement the `cp-tools genhtml` command

### Description:
Currently, cp-tools has the commands `genpdf` and `gentex`, where the files are compiled for PDF and LaTEX respectively.

It is desirable that the `genhtml` command compiles the files into HTML files, so that the problem can be viewed in a browser

This CLI command should work in the same way as `genpdf` and` gentex` commands.

The parameters for this command are:
- `-h / --help` to print to the terminal the parameters supported by the command
- `-b / --label` to define the problem labels. If omitted, the default label is `A`
- `-l / --list` to list all document classes (templates) available for use
- `-c / --class` to define the class (template) of the document that will be used in the compilation. If omitted, the default template will be `plain`
- `-g / --lang` to define the language of the document. If omitted, the default language will be `pt_BR`
- `-o / --output` to define the name of the output file that will be generated. If omitted, the output file will be `problem.html`
- `-t / --tutorial` to generate the problem solution file (in html, of course)
- `--no_autor` to omit the problem author in the output file
- `--no_contest` to omit the problem contest in the output file

### Acceptance criteria:

- [ ] It must document the implemented parameters
- [ ] The files must be standalone

### Tasks:

- [ ]  Implement a LaTeX to HTML converter or use a external command to make this conversion
- [ ]  Use MathJax to display mathematical formulas in HTML

**Comment by durvalcarvalho** [comment]
@edsomjr Eu escrevi a primeira versão dessa issue. É muito imporante que as issue sejam bem definidas para incentivar as contribuições.

Eu tive um pouco de dificuldade em definir o que exatamente deve ser implementado. Acredito que somente você seria capaz de detalhar essa issue

**Comment by edsomjr** [comment]
Durval,

para não duplicar texto apliquei as modificações diretamente no seu texto. Agora acho que está razoavelmente claro o objetivo desta issue.
