### ISSUE TITLE
Add the opton '-s' to the 'check' command

### ISSUE THREAD

**Issue by edsomjr** [edsomjr/competitive-problems-tools#27]
### Description:
This option should check all solutions defined in the `config.json` file
Currently, the `cp-tools check` command supports only the following flags:
- `-c / --checker`;
- `-h / --help`;
- `-t / --tests`;
- `-v / --validator`;

It is desirable that the `cp-tools check -s` command validates all solutions defined in the file `config.json`, in the key `solutions: {}`. Currently, each solution must be checked with the command:
```
cp-tools judge solution.[cpp|java|py]
```

Remembering that there are several types of solutions (WA, AC, TLE, etc.), the validation of a solution depends on its type, for example, a positive validation of a TLE solution is one that does not pass the test set because it goes beyond the defined maximum time

### Acceptance criteria:
- [ ] It must document the implemented parameters
- [ ] It must add tests for each type of solution

### Tasks:

- [ ]  Run the subroutine of `judge` command to check each solution described in `config.json` 
- [ ]  Write templates for each type of solution
- [ ] Write unit tests for each type of solution

**Comment by durvalcarvalho** [comment]
## Add the option `-s` to the `check` command

### Description:
This option should check all solutions defined in the `config.json` file
Currently, the `cp-tools check` command supports only the following flags:
- `-c / --checker`;
- `-h / --help`;
- `-t / --tests`;
- `-v / --validator`;

It is desirable that the `cp-tools check -s` command validates all solutions defined in the file `config.json`, in the key `solutions: {}`. Currently, each solution must be checked with the command:
```
cp-tools judge solution.[cpp|java|py]
```

Remembering that there are several types of solutions (WA, AC, TLE, etc.), the validation of a solution depends on its type, for example, a positive validation of a TLE solution is one that does not pass the test set because it goes beyond the defined maximum time

### Acceptance criteria:
- [ ] It must document the implemented parameters
- [ ] It must add tests for each type of solution

### Tasks:

- [ ]  Run the subroutine of `judge` command to check each solution described in `config.json` 
- [ ]  Write templates for each type of solution
- [ ] Write unit tests for each type of solution

**Comment by durvalcarvalho** [comment]
@edsomjr eu escrevi essa primeira versão dessa issue. Eu to tendo dificuldade para entender o que exatamente deve ser feito nessa issue. Eu dei uma olhada no arquivo `config.json` e vi que é definido um arquivo que será a solução padrão... É para ter mais de uma solução padrão?

**Comment by edsomjr** [comment]
Durval,

atualizei o texto da issue.
